### ISSUE TITLE
 IRC commands not working (read: probably need help with permissions)

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#23]
From report:

```
04.01.2014 17:26:52  [Logger/DEBUG] Got IRC Message from #citaborg: .players
04.01.2014 17:26:52  [Logger/DEBUG] Got a new relay Message from IRC: Citaborg: .players
04.01.2014 17:26:52  [Logger/DEBUG] Got Minecraft Message sending it to #citaborg: Citaborg: You have not enough Permissions to execute this
```

My ircPerm file:

```
Groups:
  default:
    Rank: 1
    Permissions:
    - command.players
    Inherits: []
Users:  
  Citaborg:
    Groups:
    - default
    Permissions:
    - command.players
    - command.mute
    - command.unmute
    - command.message
```

Citaborg is a registered nick With espernets NickServ

```
/msg NickServ Acc Citaborg
-NickServ- Citaborg ACC 3

/whois Citaborg
Citaborg is skattefute@cm-84.211.113.190.getinternet.no * Skattefuten
Citaborg on #citaborg #md_5 #spigot 
Citaborg using availo.esper.net We've got the most recently updated description!
Citaborg has been idle 14secs, signed on Sat Dec 28 13:43:26
Citaborg is logged in as Citaborg
Citaborg End of /WHOIS list.
```
