### ISSUE TITLE
[Enhancement] Permissions

### ISSUE THREAD

**Issue by Hatventures** [geNAZt/CloudChat#62]
2 Parts:

1) Whenever a permission is changed (for instance, adding a channel permission to a player), said player is required to relog to get the effect (cannot join said channel until then).
While this is a minor problem on paper, there is some cases that I have in mind (allowing the use of a channel or command for a limited period of time) where it could make it a bit awkward for the players.

2) Extremly complete chat plugin, i'll give you that. I feel that you could make it a tad easier on the server monkey person by adding 3 meta permissions containers:

admin, moderator and user.
While this setup wouldnt be for 100% of the servers, I feel it would cover _most_

Here is the suggestion:

**cloudchat.rank.admin**
- Any and all permissions

**cloudchat.rank.moderator**
cloudchat.command.mute
cloudchat.command.unmute
cloudchat.command.broadcast
cloudchat.command.clearchat.other
cloudchat.canleaveforced
cloudchat.cannot.muted
cloudchat.ignore.maxchannel
cloudchat.command.nick
cloudchat.command.nick.other
cloudchat.command.createchannel

**cloudchat.rank.user**
cloudchat.command.join
cloudchat.command.leave
cloudchat.command.msg
cloudchat.command.reply
cloudchat.command.focus
cloudchat.command.clearchat
cloudchat.command.channels
cloudchat.command.invite
cloudchat.command.togglepm

(obviously, this is just a proposal, if you choose to actually implement such a thing, the permissions are at your discretion ;) Just wanted to help a bit)

**Comment by geNAZt** [comment]
1) Whenever a permission is changed (for instance, adding a channel permission to a player), said player is required to relog to get the effect (cannot join said channel until then).
While this is a minor problem on paper, there is some cases that I have in mind (allowing the use of a channel or command for a limited period of time) where it could make it a bit awkward for the players.

This is wrong. When the Player changes the Server or World its Permissions get reloaded. Also i don't know when the Permissions change for said User so i would be forced to check the Permissions at a frequent interval which would cause much traffic and lag on both sides. If Vault would implement a PermissionChangedEvent or something that would be awesome :D

2) I will not implement static Permission container. Thats against the nature of the CloudChat plugin. I will add a config for those Container and will lay this Template into it. Thanks for the Suggestion :)

**Comment by Hatventures** [comment]
Fair enough good sir!

**Comment by geNAZt** [comment]
Can you leave this open please ? Thanks :P

**Comment by geNAZt** [comment]
2 ) Part completed: Added permissionContainers.yml

```
# Config for Permission Containers
# You give a Player the Access Permission and it will get all the Sub Permissions

PermissionContainers:
- Access: cloudchat.rank.admin
  Sub:
  - cloudchat.*
- Access: cloudchat.rank.moderator
  Sub:
  - cloudchat.command.broadcast
  - cloudchat.command.clearchat.other
  - cloudchat.rank.user
  - cloudchat.canleaveforced
  - cloudchat.cannot.muted
  - cloudchat.ignore.maxchannel
  - cloudchat.command.nick
  - cloudchat.command.nick.other
  - cloudchat.command.createchannel
  - cloudchat.command.cc.mute
  - cloudchat.command.cc.unmute
- Access: cloudchat.rank.user
  Sub:
  - cloudchat.command.join
  - cloudchat.command.leave
  - cloudchat.command.focus
  - cloudchat.command.msg
  - cloudchat.command.reply
  - cloudchat.command.channels
  - cloudchat.command.clearchat
  - cloudchat.command.invite
  - cloudchat.command.togglepm
```
