### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by Citaborg** [geNAZt/CloudChat#9]
Running 1.7\* and 0.5.1 all Messages are duplicated

![capture](https://f.cloud.github.com/assets/3041020/1798800/7cfa33e0-6b6f-11e3-9971-b242d5a1b992.PNG)

It almost feels like the CloudChatBukkit is not there (apart from the Message being transmitted to IRC)

Chat bungee config:

```
MaxChannelsPerChatter: 4
DoNotBind: []

Announce:
  PlayerJoin: true
  PlayerJoinMessage: '&8[&2%channel_short&8]&r %prefix%nick%suffix&r joined the Server'
  PlayerQuit: true
  PlayerQuitMessage: '&8[&2%channel_short&8]&r %prefix%nick%suffix&r left the Server'
  PlayerGotAfk: '&8[&2%channel_short&8]&r %prefix%nick%suffix&r is afk'
  PlayerGotOutOfAfk: '&8[&2%channel_short&8]&r %prefix%nick%suffix&r no longer is afk'

DontHandleForServers: []
FactionServers: []
```

Chat bukkit config:

```
BlockPlayerJoin: false
BlockPlayerQuit: false
HandleAFK: false
AutoAFK: 0
```

(Reverting to previous Version (1.6.1) With untouched config Works)
